In [1]:
import pandas as pd
import numpy as np

In [2]:
import cv2
import mediapipe as mp
import time
import csv
import matplotlib.pyplot as plt

In [3]:
import tensorflow as tf

In [4]:
import h5py

In [4]:
print("hello")

hello


In [5]:
df_normalized = pd.read_csv("datasets\\final_combined_res2.csv")

In [6]:
df_normalized = df_normalized.iloc[:, 2:]

In [7]:
df_normalized

1         2         3         4         5         6         7  \
0      bad -31.72711 -43.93206 -14.33884 -32.56898 -47.56874 -20.99366   
1      bad -30.54964 -45.36607  -9.68939 -31.28414 -48.88999 -16.33501   
2      bad -29.58770 -46.13976  -8.21485 -30.16713 -49.59452 -14.77991   
3      bad -28.45797 -46.04477  -5.32259 -29.07712 -49.46539 -12.16800   
4      bad -28.28699 -46.64859  -6.07582 -28.75479 -49.99658 -12.82403   
...    ...       ...       ...       ...       ...       ...       ...   
7661  good  -8.00878 -53.88042 -67.06887  -5.51446 -57.57016 -68.00975   
7662  good  -8.13522 -54.89783 -68.85780  -5.40114 -58.34312 -70.23661   
7663  good  -8.68579 -55.98842 -68.83918  -5.79288 -59.29224 -70.41462   
7664  good  -9.16142 -56.52751 -66.09471  -6.47916 -59.82820 -70.71228   
7665  good  -9.04805 -56.17644 -64.09562  -6.57860 -59.51007 -67.46810   

             8         9        10  ...        91        92        93  \
0    -32.36458 -47.89844 -20.98893  ...  20.83981 -19.40891  34.85072   
1    -31.09864 -49.13038 -16.33511  ...  23.54814 -16.84375  30.52527   
2    -29.95729 -49.80436 -14.78331  ...  23.04086 -16.65932  31.68052   
3    -28.88301 -49.68644 -12.17297  ...  23.94671 -16.88494  34.08302   
4    -28.57970 -50.07245 -12.82743  ...  24.84329 -16.55430  32.52426   
...        ...       ...       ...  ...       ...       ...       ...   
7661  -4.22762 -57.77262 -68.00247  ... -27.43107 -27.77397  40.54153   
7662  -4.12681 -58.47282 -70.22753  ... -25.45034 -28.10422  40.18725   
7663  -4.50719 -59.36934 -70.40376  ... -24.62943 -28.49677  40.87766   
7664  -5.20769 -59.92564 -70.70310  ... -26.77794 -29.14105  41.31355   
7665  -5.30301 -59.61536 -67.45462  ... -23.90637 -29.16875  41.57428   

            94        95        96        97        98        99       100  
0     43.37444 -35.95567  47.68234  27.68480 -30.29016  42.02842  44.43602  
1     49.75788 -34.42049  43.38252  32.38142 -28.65924  36.38164  56.09230  
2     46.92944 -33.05189  43.56117  31.65580 -29.13514  37.48433  51.22749  
3     45.83032 -32.81037  41.91866  32.86817 -30.32473  39.37947  50.09533  
4     49.11812 -32.79066  41.71798  34.05568 -29.30259  38.18723  53.58683  
...        ...       ...       ...       ...       ...       ...       ...  
7661  12.43542 -29.90525  60.95736 -38.52452 -45.02608  49.00163   2.51274  
7662  14.40244 -30.26182  61.28120 -36.81328 -45.10877  48.98943   4.23188  
7663  14.80669 -30.70159  61.53155 -36.70191 -45.74370  49.37399   3.91116  
7664  14.07909 -31.33755  62.00835 -38.63052 -46.52744  49.27484   3.85987  
7665  16.88039 -31.60298  62.76501 -35.25722 -46.28182  50.28761   7.20259  

[7666 rows x 100 columns]

In [8]:
train_normalized = df_normalized.iloc[:, 1:]
train_labels = df_normalized.iloc[:, 0]

In [31]:
train_normalized

2         3         4         5         6         7         8  \
0    -31.72711 -43.93206 -14.33884 -32.56898 -47.56874 -20.99366 -32.36458   
1    -30.54964 -45.36607  -9.68939 -31.28414 -48.88999 -16.33501 -31.09864   
2    -29.58770 -46.13976  -8.21485 -30.16713 -49.59452 -14.77991 -29.95729   
3    -28.45797 -46.04477  -5.32259 -29.07712 -49.46539 -12.16800 -28.88301   
4    -28.28699 -46.64859  -6.07582 -28.75479 -49.99658 -12.82403 -28.57970   
...        ...       ...       ...       ...       ...       ...       ...   
7661  -8.00878 -53.88042 -67.06887  -5.51446 -57.57016 -68.00975  -4.22762   
7662  -8.13522 -54.89783 -68.85780  -5.40114 -58.34312 -70.23661  -4.12681   
7663  -8.68579 -55.98842 -68.83918  -5.79288 -59.29224 -70.41462  -4.50719   
7664  -9.16142 -56.52751 -66.09471  -6.47916 -59.82820 -70.71228  -5.20769   
7665  -9.04805 -56.17644 -64.09562  -6.57860 -59.51007 -67.46810  -5.30301   

             9        10        11  ...        91        92        93  \
0    -47.89844 -20.98893 -32.14192  ...  20.83981 -19.40891  34.85072   
1    -49.13038 -16.33511 -30.88980  ...  23.54814 -16.84375  30.52527   
2    -49.80436 -14.78331 -29.72392  ...  23.04086 -16.65932  31.68052   
3    -49.68644 -12.17297 -28.66605  ...  23.94671 -16.88494  34.08302   
4    -50.07245 -12.82743 -28.37545  ...  24.84329 -16.55430  32.52426   
...        ...       ...       ...  ...       ...       ...       ...   
7661 -57.77262 -68.00247  -2.89614  ... -27.43107 -27.77397  40.54153   
7662 -58.47282 -70.22753  -2.80668  ... -25.45034 -28.10422  40.18725   
7663 -59.36934 -70.40376  -3.17434  ... -24.62943 -28.49677  40.87766   
7664 -59.92564 -70.70310  -3.88012  ... -26.77794 -29.14105  41.31355   
7665 -59.61536 -67.45462  -3.97252  ... -23.90637 -29.16875  41.57428   

            94        95        96        97        98        99       100  
0     43.37444 -35.95567  47.68234  27.68480 -30.29016  42.02842  44.43602  
1     49.75788 -34.42049  43.38252  32.38142 -28.65924  36.38164  56.09230  
2     46.92944 -33.05189  43.56117  31.65580 -29.13514  37.48433  51.22749  
3     45.83032 -32.81037  41.91866  32.86817 -30.32473  39.37947  50.09533  
4     49.11812 -32.79066  41.71798  34.05568 -29.30259  38.18723  53.58683  
...        ...       ...       ...       ...       ...       ...       ...  
7661  12.43542 -29.90525  60.95736 -38.52452 -45.02608  49.00163   2.51274  
7662  14.40244 -30.26182  61.28120 -36.81328 -45.10877  48.98943   4.23188  
7663  14.80669 -30.70159  61.53155 -36.70191 -45.74370  49.37399   3.91116  
7664  14.07909 -31.33755  62.00835 -38.63052 -46.52744  49.27484   3.85987  
7665  16.88039 -31.60298  62.76501 -35.25722 -46.28182  50.28761   7.20259  

[7666 rows x 99 columns]

In [45]:
train_labels = train_labels.to_numpy()

In [46]:
train_labels

array(['bad', 'bad', 'bad', ..., 'good', 'good', 'good'], dtype=object)

In [9]:
test_df_norm = pd.read_csv("datasets\\final_combined_res_test.csv")

In [10]:
test_df_norm = test_df_norm.iloc[:, 2:]

In [11]:
test_df_norm

1         2         3         4         5         6         7  \
0      bad -47.01977 -37.25197 -20.66531 -46.10595 -41.42131 -26.27069   
1      bad -45.25699 -37.48175 -14.23429 -44.59497 -41.43215 -19.28928   
2      bad -44.98607 -39.52522 -17.51670 -44.38329 -43.48280 -23.27364   
3      bad -44.41467 -40.15785 -18.98139 -43.77096 -44.19825 -24.43582   
4      bad -44.05031 -40.89419 -14.87221 -43.49860 -44.83008 -20.85129   
...    ...       ...       ...       ...       ...       ...       ...   
5893  good -10.34873 -52.18179 -28.79293 -13.38223 -54.58076 -27.55863   
5894  good -10.34206 -52.07777 -28.14812 -13.36393 -54.47958 -26.78352   
5895  good -10.35263 -52.00562 -29.70384 -13.36843 -54.41077 -28.42311   
5896  good -10.42279 -51.91599 -30.05323 -13.43795 -54.31793 -28.81223   
5897  good -10.51413 -51.90405 -32.36855 -13.54751 -54.32606 -31.32781   

             8         9        10  ...        91        92        93  \
0    -45.37806 -41.60362 -26.26408  ...  16.18619 -25.18408  32.28055   
1    -44.00153 -41.76665 -19.27257  ...   4.39617 -12.73234  25.97185   
2    -43.83656 -43.73378 -23.26596  ...  15.53384 -23.62491  28.66159   
3    -43.22923 -44.40026 -24.43980  ...  14.09455 -23.94583  29.79265   
4    -43.04387 -45.05270 -20.83648  ...  12.87660 -23.05597  29.18120   
...        ...       ...       ...  ...       ...       ...       ...   
5893 -13.53046 -54.65786 -27.54345  ...  63.12007  32.27460  42.12569   
5894 -13.51616 -54.55620 -26.77084  ...  59.72969  31.83628  41.71904   
5895 -13.52353 -54.48873 -28.41080  ...  62.71144  31.71589  41.75035   
5896 -13.59917 -54.39618 -28.79992  ...  61.71392  31.59736  41.68653   
5897 -13.70062 -54.40649 -31.31279  ...  67.71445  31.80533  42.06927   

            94        95        96        97        98        99       100  
0     39.39287 -38.76936  51.79115  21.59189 -39.67407  39.43896  42.90172  
1     38.66400 -37.49078  51.38464   4.01721 -21.09019  32.96227  39.95684  
2     40.91911 -36.94512  52.74177  16.42086 -39.31703  35.94695  41.62103  
3     40.39886 -36.85031  53.53437  12.97308 -39.80728  35.09620  40.28785  
4     40.62175 -36.16595  53.08139  13.83988 -38.31093  34.35829  40.85315  
...        ...       ...       ...       ...       ...       ...       ...  
5893  -0.82604  32.35675  22.19985  68.15981  51.19506  40.60580  -6.14023  
5894  -1.93699  38.44150  22.61106  61.89596  50.94942  40.41217  -7.42266  
5895  -1.87257  35.66459  22.11637  66.57320  50.76919  40.37033  -7.40555  
5896  -1.65917  36.74593  22.25803  64.88148  50.46173  40.32098  -6.70008  
5897   0.47504  36.18233  20.74204  73.89140  50.76367  40.55772  -4.52657  

[5898 rows x 100 columns]

In [12]:
test_normalized = test_df_norm.iloc[:, 1:]
test_labels = test_df_norm.iloc[:, 0]

In [49]:
type(test_normalized.iloc[0, 0])

numpy.float64

In [43]:
test_labels = test_labels.to_numpy()

In [98]:
test_labels

0        bad
1        bad
2        bad
3        bad
4        bad
        ... 
5893    good
5894    good
5895    good
5896    good
5897    good
Name: 1, Length: 5898, dtype: object

In [13]:
input_shape = len(train_normalized.iloc[0, :])
input_shape

99

In [14]:
dense_nn = tf.keras.Sequential([
            tf.keras.Input(shape=input_shape),
            tf.keras.layers.Dense(100, activation="relu"),
            tf.keras.layers.Dense(100, activation="relu"),
            tf.keras.layers.Dense(100, activation="relu"),
            tf.keras.layers.Dense(2, activation="softmax")
    ])

In [15]:
dense_nn.compile(optimizer="adam", loss="sparse_categorical_crossentropy", metrics=["accuracy"])

In [53]:
train_normalized = tf.convert_to_tensor(train_normalized)
train_normalized

<tf.Tensor: shape=(7666, 99), dtype=float64, numpy=
array([[-31.72711, -43.93206, -14.33884, ..., -30.29016,  42.02842,
         44.43602],
       [-30.54964, -45.36607,  -9.68939, ..., -28.65924,  36.38164,
         56.0923 ],
       [-29.5877 , -46.13976,  -8.21485, ..., -29.13514,  37.48433,
         51.22749],
       ...,
       [ -8.68579, -55.98842, -68.83918, ..., -45.7437 ,  49.37399,
          3.91116],
       [ -9.16142, -56.52751, -66.09471, ..., -46.52744,  49.27484,
          3.85987],
       [ -9.04805, -56.17644, -64.09562, ..., -46.28182,  50.28761,
          7.20259]])>

In [19]:
train_labels[train_labels == "bad"] = 0.0

C:\Users\Rithik\AppData\Local\Temp\ipykernel_26040\896725040.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_labels[train_labels == "bad"] = 0.0


In [20]:
train_labels[train_labels == "good"] = 1.0

C:\Users\Rithik\AppData\Local\Temp\ipykernel_26040\3360462734.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_labels[train_labels == "good"] = 1.0


In [21]:
train_labels

0       0.0
1       0.0
2       0.0
3       0.0
4       0.0
       ... 
7661    1.0
7662    1.0
7663    1.0
7664    1.0
7665    1.0
Name: 1, Length: 7666, dtype: object

In [22]:
test_labels[test_labels == "bad"] = 0.0
test_labels[test_labels == "good"] = 1.0

C:\Users\Rithik\AppData\Local\Temp\ipykernel_26040\2406337438.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_labels[test_labels == "bad"] = 0.0
C:\Users\Rithik\AppData\Local\Temp\ipykernel_26040\2406337438.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_labels[test_labels == "good"] = 1.0


In [23]:
train_labels_1 = train_labels.to_numpy().astype("float64")
train_labels_1

array([0., 0., 0., ..., 1., 1., 1.])

In [24]:
test_labels_1 = test_labels.to_numpy().astype("float64")
test_labels_1

array([0., 0., 0., ..., 1., 1., 1.])

In [73]:
train_normalized

2         3         4         5         6         7         8  \
0    -31.72711 -43.93206 -14.33884 -32.56898 -47.56874 -20.99366 -32.36458   
1    -30.54964 -45.36607  -9.68939 -31.28414 -48.88999 -16.33501 -31.09864   
2    -29.58770 -46.13976  -8.21485 -30.16713 -49.59452 -14.77991 -29.95729   
3    -28.45797 -46.04477  -5.32259 -29.07712 -49.46539 -12.16800 -28.88301   
4    -28.28699 -46.64859  -6.07582 -28.75479 -49.99658 -12.82403 -28.57970   
...        ...       ...       ...       ...       ...       ...       ...   
7661  -8.00878 -53.88042 -67.06887  -5.51446 -57.57016 -68.00975  -4.22762   
7662  -8.13522 -54.89783 -68.85780  -5.40114 -58.34312 -70.23661  -4.12681   
7663  -8.68579 -55.98842 -68.83918  -5.79288 -59.29224 -70.41462  -4.50719   
7664  -9.16142 -56.52751 -66.09471  -6.47916 -59.82820 -70.71228  -5.20769   
7665  -9.04805 -56.17644 -64.09562  -6.57860 -59.51007 -67.46810  -5.30301   

             9        10        11  ...        91        92        93  \
0    -47.89844 -20.98893 -32.14192  ...  20.83981 -19.40891  34.85072   
1    -49.13038 -16.33511 -30.88980  ...  23.54814 -16.84375  30.52527   
2    -49.80436 -14.78331 -29.72392  ...  23.04086 -16.65932  31.68052   
3    -49.68644 -12.17297 -28.66605  ...  23.94671 -16.88494  34.08302   
4    -50.07245 -12.82743 -28.37545  ...  24.84329 -16.55430  32.52426   
...        ...       ...       ...  ...       ...       ...       ...   
7661 -57.77262 -68.00247  -2.89614  ... -27.43107 -27.77397  40.54153   
7662 -58.47282 -70.22753  -2.80668  ... -25.45034 -28.10422  40.18725   
7663 -59.36934 -70.40376  -3.17434  ... -24.62943 -28.49677  40.87766   
7664 -59.92564 -70.70310  -3.88012  ... -26.77794 -29.14105  41.31355   
7665 -59.61536 -67.45462  -3.97252  ... -23.90637 -29.16875  41.57428   

            94        95        96        97        98        99       100  
0     43.37444 -35.95567  47.68234  27.68480 -30.29016  42.02842  44.43602  
1     49.75788 -34.42049  43.38252  32.38142 -28.65924  36.38164  56.09230  
2     46.92944 -33.05189  43.56117  31.65580 -29.13514  37.48433  51.22749  
3     45.83032 -32.81037  41.91866  32.86817 -30.32473  39.37947  50.09533  
4     49.11812 -32.79066  41.71798  34.05568 -29.30259  38.18723  53.58683  
...        ...       ...       ...       ...       ...       ...       ...  
7661  12.43542 -29.90525  60.95736 -38.52452 -45.02608  49.00163   2.51274  
7662  14.40244 -30.26182  61.28120 -36.81328 -45.10877  48.98943   4.23188  
7663  14.80669 -30.70159  61.53155 -36.70191 -45.74370  49.37399   3.91116  
7664  14.07909 -31.33755  62.00835 -38.63052 -46.52744  49.27484   3.85987  
7665  16.88039 -31.60298  62.76501 -35.25722 -46.28182  50.28761   7.20259  

[7666 rows x 99 columns]

In [25]:
dense = dense_nn.fit(train_normalized, train_labels_1, epochs=10, validation_data=(test_normalized, test_labels_1))

Epoch 1/10
240/240 [==============================] - 1s 4ms/step - loss: 0.1230 - accuracy: 0.9791 - val_loss: 0.2400 - val_accuracy: 0.9607
Epoch 2/10
240/240 [==============================] - 1s 3ms/step - loss: 0.0033 - accuracy: 0.9986 - val_loss: 0.2725 - val_accuracy: 0.9491
Epoch 3/10
240/240 [==============================] - 1s 3ms/step - loss: 8.5853e-05 - accuracy: 1.0000 - val_loss: 0.1535 - val_accuracy: 0.9661
Epoch 4/10
240/240 [==============================] - 1s 3ms/step - loss: 3.7353e-05 - accuracy: 1.0000 - val_loss: 0.1502 - val_accuracy: 0.9683
Epoch 5/10
240/240 [==============================] - 1s 3ms/step - loss: 2.8386e-05 - accuracy: 1.0000 - val_loss: 0.1624 - val_accuracy: 0.9659
Epoch 6/10
240/240 [==============================] - 1s 3ms/step - loss: 2.2591e-05 - accuracy: 1.0000 - val_loss: 0.1409 - val_accuracy: 0.9691
Epoch 7/10
240/240 [==============================] - 1s 3ms/step - loss: 1.8439e-05 - accuracy: 1.0000 - val_loss: 0.1574 - val_acc

In [122]:
!pip install h5py

In [26]:
dense_nn.save("final_nn.keras")

In [125]:
from importlib import reload
reload(tf.keras.models)

<module 'keras.api._v2.keras.models' from 'C:\\Users\\Rithik\\Anaconda3\\envs\\tf\\lib\\site-packages\\keras\\api\\_v2\\keras\\models\\__init__.py'>

In [128]:
dense_nn.to_json()

'{"class_name": "Sequential", "config": {"name": "sequential", "layers": [{"class_name": "InputLayer", "config": {"batch_input_shape": [null, 99], "dtype": "float32", "sparse": false, "ragged": false, "name": "input_1"}}, {"class_name": "Dense", "config": {"name": "dense", "trainable": true, "dtype": "float32", "units": 100, "activation": "relu", "use_bias": true, "kernel_initializer": {"class_name": "GlorotUniform", "config": {"seed": null}}, "bias_initializer": {"class_name": "Zeros", "config": {}}, "kernel_regularizer": null, "bias_regularizer": null, "activity_regularizer": null, "kernel_constraint": null, "bias_constraint": null}}, {"class_name": "Dense", "config": {"name": "dense_1", "trainable": true, "dtype": "float32", "units": 100, "activation": "relu", "use_bias": true, "kernel_initializer": {"class_name": "GlorotUniform", "config": {"seed": null}}, "bias_initializer": {"class_name": "Zeros", "config": {}}, "kernel_regularizer": null, "bias_regularizer": null, "activity_regu

In [29]:
converter = tf.lite.TFLiteConverter.from_keras_model(dense_nn)

In [30]:
tflite_model = converter.convert()

# Save the model.
with open('final_nn_model.tflite', 'wb') as f:
  f.write(tflite_model)

INFO:tensorflow:Assets written to: C:\Users\Rithik\AppData\Local\Temp\tmpg_k59q8d\assets


INFO:tensorflow:Assets written to: C:\Users\Rithik\AppData\Local\Temp\tmpg_k59q8d\assets


In [31]:
interpreter = tf.lite.Interpreter(model_path = 'final_nn_model.tflite')
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()
print("Input Shape: ", input_details[0]['shape'])
print("Input Type: ", input_details[0]['dtype'])
print("Output Shape: ", output_details[0]['shape'])
print("Output Type: ", output_details[0]['dtype'])

Input Shape:  [ 1 99]
Input Type:  <class 'numpy.float32'>
Output Shape:  [1 2]
Output Type:  <class 'numpy.float32'>
